spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      properties:
        format_sql: true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: test
    password: test1234!

